import { CATEGORIES, SETTINGS_MAP } from "./schema";
import { getChangedEntries, getMappings } from "./state";
import { getActionLua } from "./mappings";

// Keys that are grouped into window_padding table
const PADDING_KEYS = new Set([
  "window_padding_left",
  "window_padding_right",
  "window_padding_top",
  "window_padding_bottom",
]);

function luaValue(key: string, value: string): string {
  const setting = SETTINGS_MAP.get(key);
  if (!setting) return `'${escapeLuaString(value)}'`;

  // Special: font_family generates wezterm.font()
  if (key === "font_family") {
    return `wezterm.font('${escapeLuaString(value)}')`;
  }

  // Special: default_prog generates a Lua table from comma-separated values
  if (key === "default_prog" && value) {
    const parts = value.split(",").map((s) => `'${escapeLuaString(s.trim())}'`);
    return `{ ${parts.join(", ")} }`;
  }

  // Special: harfbuzz_features generates a Lua table
  if (key === "harfbuzz_features" && value) {
    const parts = value.split(",").map((s) => `'${escapeLuaString(s.trim())}'`);
    return `{ ${parts.join(", ")} }`;
  }

  switch (setting.type) {
    case "bool":
      return value === "true" ? "true" : "false";
    case "int":
      return String(parseInt(value, 10));
    case "float": {
      const n = parseFloat(value);
      return Number.isInteger(n) ? `${n}.0` : String(n);
    }
    case "enum":
      // color_scheme and string enums use quoted strings
      return `'${escapeLuaString(value)}'`;
    case "string":
      return `'${escapeLuaString(value)}'`;
    default:
      return `'${escapeLuaString(value)}'`;
  }
}

function escapeLuaString(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

export function generateConfig(): string {
  const changed = new Map(getChangedEntries());
  const validMappings = getMappings().filter((m) => m.key && m.action);

  if (changed.size === 0 && validMappings.length === 0) {
    return "-- All settings at defaults.\n-- Change some settings to generate config\n";
  }

  const lines: string[] = [
    "-- Generated by wez-conf (https://wez-conf.balintb.com/)",
    "local wezterm = require 'wezterm'",
    "local config = wezterm.config_builder()",
    "",
  ];

  // Check if we have padding changes
  const paddingChanged = new Map<string, string>();
  for (const k of PADDING_KEYS) {
    if (changed.has(k)) {
      paddingChanged.set(k, changed.get(k)!);
    }
  }

  for (const category of CATEGORIES) {
    const categoryLines: string[] = [];
    for (const setting of category.settings) {
      if (!changed.has(setting.key)) continue;

      // Skip individual padding keys — they're grouped below
      if (PADDING_KEYS.has(setting.key)) continue;

      const value = changed.get(setting.key)!;
      categoryLines.push(`config.${setting.key} = ${luaValue(setting.key, value)}`);
    }
    if (categoryLines.length > 0) {
      lines.push(`-- ${category.title}`);
      lines.push(...categoryLines);
      lines.push("");
    }
  }

  // Emit grouped window_padding if any padding value changed
  if (paddingChanged.size > 0) {
    const left = changed.get("window_padding_left") ?? "0";
    const right = changed.get("window_padding_right") ?? "0";
    const top = changed.get("window_padding_top") ?? "0";
    const bottom = changed.get("window_padding_bottom") ?? "0";
    lines.push("-- Window Padding");
    lines.push(`config.window_padding = {`);
    lines.push(`  left = ${left},`);
    lines.push(`  right = ${right},`);
    lines.push(`  top = ${top},`);
    lines.push(`  bottom = ${bottom},`);
    lines.push(`}`);
    lines.push("");
  }

  if (validMappings.length > 0) {
    lines.push("-- Key Bindings");
    lines.push("config.keys = {");
    for (const m of validMappings) {
      const lua = getActionLua(m.action);
      if (m.mods) {
        lines.push(`  { key = '${escapeLuaString(m.key)}', mods = '${m.mods}', action = ${lua} },`);
      } else {
        lines.push(`  { key = '${escapeLuaString(m.key)}', action = ${lua} },`);
      }
    }
    lines.push("}");
    lines.push("");
  }

  lines.push("return config");
  lines.push("");

  return lines.join("\n");
}
