// Curated list of popular WezTerm built-in color schemes.
// WezTerm ships 700+ schemes; this is a searchable subset of the most popular ones.
// Users can also type any scheme name manually.
export const COLOR_SCHEMES: string[] = [
  "Adventure",
  "Afterglow",
  "AlienBlood",
  "Argonaut",
  "Arthur",
  "AtelierSulphurpool",
  "Atom",
  "Ayu Dark (Gogh)",
  "Ayu Mirage",
  "Batman",
  "Belafonte Day",
  "Belafonte Night",
  "Blazer",
  "Borland",
  "Breeze",
  "Bright Lights",
  "Broadcast",
  "Brogrammer",
  "Builtin Dark",
  "Builtin Light",
  "Builtin Pastel Dark",
  "Builtin Solarized Dark",
  "Builtin Solarized Light",
  "Builtin Tango Dark",
  "Builtin Tango Light",
  "C64",
  "Catppuccin Frappe",
  "Catppuccin Latte",
  "Catppuccin Macchiato",
  "Catppuccin Mocha",
  "Chalk",
  "Chalkboard",
  "CLRS",
  "Cobalt 2",
  "Cobalt Neon",
  "CrayonPonyFish",
  "Cyberdyne",
  "cyberpunk",
  "Dark Pastel",
  "Dark+",
  "Darkside",
  "deep",
  "Desert",
  "DimmedMonokai",
  "Django",
  "DjangoRebornAgain",
  "DjangoSmooth",
  "Doom Peacock",
  "Doom One",
  "Dracula",
  "Dracula (Official)",
  "Dracula+",
  "DuoTone Dark",
  "Earthsong",
  "Elemental",
  "Elementary",
  "ENCOM",
  "Espresso",
  "Espresso Libre",
  "Everblush",
  "Everforest Dark (Gogh)",
  "Everforest Light (Gogh)",
  "Fahrenheit",
  "Fairy Floss (Gogh)",
  "Fideloper",
  "Firefly Traditional",
  "FishTank",
  "Flat",
  "Flatland",
  "Floraverse",
  "Forest Night (Gogh)",
  "FrontEndDelight",
  "GitHub Dark",
  "GitHub Light",
  "Glacier",
  "Grape",
  "Grass",
  "Grey-green",
  "Gruvbox Dark (Gogh)",
  "Gruvbox dark, hard (base16)",
  "Gruvbox dark, medium (base16)",
  "Gruvbox dark, soft (base16)",
  "Gruvbox Light",
  "Gruvbox light, hard (base16)",
  "Guezwhoz",
  "Hardcore",
  "Harper",
  "Hipster Green",
  "Homebrew",
  "Horizon Dark (Gogh)",
  "Hurtado",
  "IC_Green_PPL",
  "IC_Orange_PPL",
  "iceberg-dark",
  "iceberg-light",
  "IR_Black",
  "Jackie Brown",
  "Japanesque",
  "JetBrains Darcula",
  "Kanagawa (Gogh)",
  "Kanagawa Dragon (Gogh)",
  "Kibble",
  "Kolorit",
  "Konsolas",
  "Lab Fox",
  "Laser",
  "Later This Evening",
  "Lavandula",
  "LiquidCarbon",
  "LiquidCarbonTransparent",
  "LiquidCarbonTransparentInverse",
  "lovelace",
  "Man Page",
  "Mariana",
  "MaterialDark",
  "MaterialDesignColors",
  "MaterialOcean",
  "Mathias",
  "Medallion",
  "Melange Dark (Gogh)",
  "Melange Light (Gogh)",
  "Mellifluous",
  "Mirage",
  "Molokai",
  "MonaLisa",
  "Monokai (terminal.sexy)",
  "Monokai Dark (Gogh)",
  "Monokai Pro (Gogh)",
  "Monokai Remastered",
  "Monokai Soda",
  "N0tch2k",
  "Neon",
  "Neon Night (Gogh)",
  "Neutron",
  "Night Owl (Gogh)",
  "Night Owlish Light",
  "Nocturnal Winter",
  "nord",
  "Nord (Gogh)",
  "Nord Light (Gogh)",
  "Novel",
  "NvimDark",
  "NvimLight",
  "Obsidian",
  "Ocean (base16)",
  "OceanicMaterial",
  "Ollie",
  "One Dark (Gogh)",
  "One Half Black (Gogh)",
  "One Half Light (Gogh)",
  "OneHalfDark",
  "OneHalfLight",
  "Overnight Slumber",
  "Palenight (Gogh)",
  "PaperColor Dark (base16)",
  "PaperColor Light (base16)",
  "Paraiso Dark (base16)",
  "PencilDark",
  "PencilLight",
  "Peppermint",
  "Piatto Light",
  "Poimandres",
  "Poimandres Storm",
  "PaleNightHC",
  "Primary",
  "Pro",
  "Pro Light",
  "Purple Rain",
  "Rapture",
  "Raycast_Dark",
  "Raycast_Light",
  "Rebecca",
  "Red Alert",
  "Relaxed",
  "Retro",
  "Rippedcasts",
  "rose-pine",
  "rose-pine-dawn",
  "rose-pine-moon",
  "Royal",
  "Ryuuko",
  "Sakura",
  "Scarlet Protocol",
  "Seafoam Pastel",
  "Seti",
  "Shaman",
  "Slate",
  "Smyck",
  "Snazzy",
  "SoftServer",
  "Solarized Dark (Gogh)",
  "Solarized Dark - Patched",
  "Solarized Dark Higher Contrast",
  "Solarized (dark) (terminal.sexy)",
  "Solarized Light (Gogh)",
  "Solarized (light) (terminal.sexy)",
  "SpaceGray",
  "SpaceGray Eighties",
  "SpaceGray Eighties Dull",
  "Spacemacs (base16)",
  "Sprout (Gogh)",
  "Square",
  "Sublette",
  "Subliminal",
  "Sundried",
  "Symphonic",
  "Tango (terminal.sexy)",
  "Tango Adapted",
  "Tango Half Adapted",
  "Terminal Basic",
  "Thayer Bright",
  "The Hulk",
  "Tokyo Night",
  "Tokyo Night (Gogh)",
  "Tokyo Night Light (Gogh)",
  "Tokyo Night Moon",
  "Tokyo Night Storm",
  "Tokyo Night Storm (Gogh)",
  "Tomorrow",
  "Tomorrow (dark) (terminal.sexy)",
  "Tomorrow Night",
  "Tomorrow Night Blue",
  "Tomorrow Night Bright",
  "Tomorrow Night Burns",
  "Tomorrow Night Eighties",
  "Treehouse",
  "Twilight (base16)",
  "Ubuntu",
  "Ultra Violet",
  "UnderTheSea",
  "Unikitty",
  "Urple",
  "Vaughn",
  "VibrantInk",
  "Violet Dark",
  "Violet Light",
  "WarmNeon",
  "Wez",
  "Whimsy",
  "WildCherry",
  "Wombat",
  "Wryan",
  "Zenburn",
  "zenwritten_dark",
  "zenwritten_light",
];
